version: "3"

tasks:
  run:
    desc: "Run program"
    cmds:
    - go run cmd/msu-logging-backend/main.go --config=./config/local.yaml
  migrate:
    desc: "Apply migrations"
    cmds:
    - go run ./cmd/migrator --mysql_conn_str="mysqladmin:mysqladmin@tcp(localhost:3306)/logging"
  runservs:
    cmds:
    - docker-compose --env-file .env.local up -d
  certs:
    cmds:
    - mkcert -cert-file ./certs/localhost.pem -key-file ./certs/localhost-key.pem localhost 127.0.0.1 ::1