env: "local"
grpc:
  port: 50051
  timeout: 10h

websocket:
  port: 443
  keyfile: "./server.key"
  certfile: "./server.crt"

message_broker:
  port: 5672
  transcribe_queue: "transcribe_queue"
  process_queue: "process_queue"