env: "local"
grpc:
  port: 50051
  timeout: 10h

websocket:
  port: 8081
  certfile: "./certs/localhost.pem"
  keyfile: "./certs/localhost-key.pem"

message_broker:
  port: 5672
  transcribe_queue: "transcribe_queue"
  process_queue: "process_queue"

HTTP:
  address: localhost:8082